import { requireRole } from "@/lib/dal";
import { getPrisma } from "@/lib/prisma";
import { AppHeader } from "@/components/AppHeader";

export default async function AgencyRankingsPage() {
  const owner = await requireRole("AGENCY");
  const prisma = getPrisma();

  const [agencies, myAgency] = await Promise.all([
    prisma.agency.findMany({
      include: { agencyAgent: { where: { status: "ACTIVE" }, select: { userId: true } } },
    }),
    prisma.agency.findUnique({ where: { ownerId: owner.id } }),
  ]);

  const allRosterIds = agencies.flatMap((a) => [a.ownerId, ...a.agencyAgent.map((m) => m.userId)]);
  const lines = await prisma.commissionLineItem.findMany({
    where: { recipientId: { in: allRosterIds } },
    select: { recipientId: true, amount: true },
  });
  const amountByUser = new Map<string, number>();
  for (const l of lines) {
    if (!l.recipientId) continue;
    amountByUser.set(l.recipientId, (amountByUser.get(l.recipientId) ?? 0) + Number(l.amount));
  }

  const ranked = agencies
    .map((a) => ({
      id: a.id,
      name: a.name,
      volume: [a.ownerId, ...a.agencyAgent.map((m) => m.userId)].reduce(
        (sum, userId) => sum + (amountByUser.get(userId) ?? 0),
        0
      ),
    }))
    .sort((a, b) => b.volume - a.volume);

  return (
    <div>
      <AppHeader title="Quarterly Rankings" />
      <div className="px-4 pt-4">
        {ranked.length === 0 && <p className="p-note">No agencies with commission volume yet.</p>}
        {ranked.map((a, i) => (
          <div key={a.id} className="row">
            <div className="row-icon">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-[17px] w-[17px]">
                <path d="M8 4h8v6a4 4 0 0 1-8 0z" />
                <path d="M8 5H4v2a4 4 0 0 0 4 4M16 5h4v2a4 4 0 0 1-4 4M10 18h4M12 14v4M8 21h8" />
              </svg>
            </div>
            <div className="min-w-0 flex-1">
              <p className="row-title">
                {i + 1}. {a.name}
                {a.id === myAgency?.id ? " (you)" : ""}
              </p>
              <p className="row-sub">RM {a.volume.toLocaleString()} volume</p>
            </div>
            {a.id === myAgency?.id && <span className="badge gold">You</span>}
          </div>
        ))}
        <div className="card mt-2">
          <p className="row-title">Qualification criteria</p>
          <p className="p-note mt-1.5 mb-0">
            Ranked by total commission volume generated by your roster. Global pool revenue share is
            reviewed quarterly.
          </p>
        </div>
      </div>
    </div>
  );
}
